//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
public class BlockLibrary
{
	public static Dictionary<int, Block> BlockDictionary;

	public static void initialize()
	{
		BlockDictionary = new Dictionary<int, Block>();
		BlockDictionary.Add (0, null);
		BlockDictionary.Add (1, new Block ());
		Block b = new Block ();
		b.negXUV = BlockUVLibrary.UVMapLibrary["stone.jpg"];
		b.posXUV = BlockUVLibrary.UVMapLibrary["stone.jpg"];
		b.negZUV = BlockUVLibrary.UVMapLibrary["stone.jpg"];
		b.posZUV = BlockUVLibrary.UVMapLibrary["stone.jpg"];
		
		b.negYUV = BlockUVLibrary.UVMapLibrary["stone.jpg"];
		b.posYUV = BlockUVLibrary.UVMapLibrary["stone.jpg"];
		BlockDictionary.Add (2, b);

		b = new Block ();
		b.negXUV = BlockUVLibrary.UVMapLibrary["sand.jpg"];
		b.posXUV = BlockUVLibrary.UVMapLibrary["sand.jpg"];
		b.negZUV = BlockUVLibrary.UVMapLibrary["sand.jpg"];
		b.posZUV = BlockUVLibrary.UVMapLibrary["sand.jpg"];
		
		b.negYUV = BlockUVLibrary.UVMapLibrary["sand.jpg"];
		b.posYUV = BlockUVLibrary.UVMapLibrary["sand.jpg"];
		BlockDictionary.Add (3, b);

		b = new Block ();
		b.negXUV = BlockUVLibrary.UVMapLibrary["wood.jpg"];
		b.posXUV = BlockUVLibrary.UVMapLibrary["wood.jpg"];
		b.negZUV = BlockUVLibrary.UVMapLibrary["wood.jpg"];
		b.posZUV = BlockUVLibrary.UVMapLibrary["wood.jpg"];
		
		b.negYUV = BlockUVLibrary.UVMapLibrary["treeinner.jpg"];
		b.posYUV = BlockUVLibrary.UVMapLibrary["treeinner.jpg"];
		BlockDictionary.Add (4, b);

		b = new Block ();
		b.negXUV = BlockUVLibrary.UVMapLibrary["leaves.jpg"];
		b.posXUV = BlockUVLibrary.UVMapLibrary["leaves.jpg"];
		b.negZUV = BlockUVLibrary.UVMapLibrary["leaves.jpg"];
		b.posZUV = BlockUVLibrary.UVMapLibrary["leaves.jpg"];
		
		b.negYUV = BlockUVLibrary.UVMapLibrary["leaves.jpg"];
		b.posYUV = BlockUVLibrary.UVMapLibrary["leaves.jpg"];
		BlockDictionary.Add (5, b);
	}
}


